TRAIN:
  ENABLE: True
  DATASET: aicity3
  BATCH_SIZE: 12
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: 'pretrain/x3d_l.pyth'
  CHECKPOINT_EPOCH_RESET: True
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: aicity3
  BATCH_SIZE: 32
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: decord
  NUM_FRAMES: 8 #TODO
  SAMPLING_RATE: 8 #TODO
  TRAIN_JITTER_SCALES: [512, 640]
  TRAIN_CROP_SIZE: 448
  TEST_CROP_SIZE: 512
  INPUT_CHANNEL_NUM: [3]
  # PATH_TO_DATA_DIR: path-to-imagenet-dir
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True # True #TODO
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
AUG:
  NUM_SAMPLE: 1
  ENABLE: False #True #TODO
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True #True #TODO
SOLVER:
  BASE_LR: 0.0005 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 50
  LR_POLICY: cosine
  WEIGHT_DECAY: 1e-5
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.00001
  OPTIMIZING_METHOD: adam #adamw? #TODO
  COSINE_AFTER_WARMUP: True
  #ZERO_WD_1D_PARAM: True
#  MOMENTUM: 0.9
MODEL:
  NUM_CLASSES: 16
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy #SoftTargetCrossEntropy,#TODO
  DROPOUT_RATE: 0.8
  USE_CHECKPOINT: False
  CHECKPOINT_NUM: [0]
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
