NUM_SHARDS=1
NUM_GPUS=2
BATCH_SIZE=12
BASE_LR=5e-4
PYTHONPATH=$PYTHONPATH:./slowfast \
CURRENT_DIR=$(cd $(dirname $0); pwd)
#echo $CURRENT_DIR
#DATA.PATH_LABEL_SEPARATOR "," \
python tools/run_net_multi_node.py \
  --init_method tcp://localhost:10125 \
  --cfg $CURRENT_DIR/config.yaml \
  --num_shards $NUM_SHARDS \
  DATA.PATH_TO_DATA_DIR /data/Disk_D/AI_city_track3/A1_cut_video_new\
  DATA.PATH_PREFIX /data/Disk_D/AI_city_track3/A1_cut_video_new \
  TRAIN.EVAL_PERIOD 1 \
  TRAIN.CHECKPOINT_PERIOD 1 \
  TRAIN.BATCH_SIZE $BATCH_SIZE \
  TRAIN.SAVE_LATEST False \
  NUM_GPUS $NUM_GPUS \
  NUM_SHARDS $NUM_SHARDS \
  SOLVER.MAX_EPOCH 50 \
  SOLVER.BASE_LR $BASE_LR \
  SOLVER.BASE_LR_SCALE_NUM_SHARDS False \
  SOLVER.WARMUP_EPOCHS 5. \
  TEST.NUM_ENSEMBLE_VIEWS 1  \
  TEST.NUM_SPATIAL_CROPS 1\
  TEST.TEST_BEST True \
  TEST.ADD_SOFTMAX True \
  TEST.BATCH_SIZE 12 \
  RNG_SEED 6666 \
  OUTPUT_DIR $CURRENT_DIR
